FROM node:22-alpine

WORKDIR /app

ARG DB_HOST
ARG DB_PORT
ARG DB_NAME
ARG DB_USER
ARG DB_PASSWORD
ARG DB_SCHEMA
ARG PORT=3333
ARG FRONTEND_ORIGIN

ENV DB_HOST=$DB_HOST
ENV DB_PORT=$DB_PORT
ENV DB_NAME=$DB_NAME
ENV DB_USER=$DB_USER
ENV DB_PASSWORD=$DB_PASSWORD
ENV DB_SCHEMA=$DB_SCHEMA
ENV PORT=$PORT
ENV FRONTEND_ORIGIN=$FRONTEND_ORIGIN
ENV NODE_ENV=production

COPY package.json ./

RUN npm install --omit=dev

COPY src ./src
COPY .env.example ./.env.example

EXPOSE 3333

CMD ["npm", "start"]

